### ISSUE TITLE
could you make the Incendiary Grenade  a seperate mod? would be really cool!

### ISSUE THREAD

**Issue by joep26020** [ControlCompany/InfectedCompany#1]

**Comment by klampzlamps** [comment]
You can now disable the infected game mechanic by setting the `infected_percent_chance` config setting to 0. This effectively keeps the mod for it's items only.

**Comment by joep26020** [comment]
> You can now disable the infected game mechanic by setting the `infected_percent_chance` config setting to 0. This effectively keeps the mod for it's items only.

thank you!
