### ISSUE TITLE
Host Always Infected? Also, potential to nerf apparatus as infected?

### ISSUE THREAD

**Issue by MrBl4ckSkull** [ControlCompany/InfectedCompany#11]
Hi, me again.

Ever since the newest update, I messed with the configs a bit. I made it so that infected players aren't guaranteed because having the chance to have no infected seemed really funny to make people paranoid.
However, one weird quirk I found (And I suppose I cannot prove it is a bug, or if we are just insanely unlucky), is that the host always seems to get infected. Perhaps its a weird quirk with the config settings we have, but here are the settings we have:
infected_for_round_percent_chance = 30
players_per_infected = 1

We played with 3 players and it seemed like the host was always infected, even though the chance should be 30%. There were also a considerable number of rounds (It definitely seemed like more than the expected 2.7% chance [0.3*0.3*0.3], but perhaps my maths is off)  where all three of us were infected (making the round end instantly. As a side note, I enabled the setting where infected do not get told their partners).

This is an aside, but the infected can grab the apparatus early and hide it to turn off all the lights in the facility. I don't mind this as a mechanic, but I was considering adding Facility Meltdown to my modpack (I haven't tested if its compatible) but if the infected can cause a detonation start the time limit, that would be way too strong. Is there a possibility to add a config to make the infected unable to pull the apparatus (whereas survivors, still can)? I know that this can be used to essentially confirm someone, but the apparatus is a rare enough item where I don't think it matters that much. I think it would add an interesting dynamic where survivors can risk taking the apparatus and getting out in time, since it is worth a lot with that mod, but prevent it being pulled by infected.

One last idea: Is there a possibility the round quota to scale with the moon you are on? Our group essentially agreed not to go to paid moons cause you get too much money there, and it is too easy to win as survivor on them. Perhaps the round quota is a proportional to the max scrap value available on the moon, instead, and make it configurable? For example 50%, so if 1000 credits worth of loot spawns on the moon, maybe survivors have to collect 500...

Just some ideas. Still love the mod :)

**Comment by klampzlamps** [comment]
1) for the percent chance, you have the setting players_per_infected to 1 which means either everyone is infected or none at all (since you have the infected per round chance at 30%). This would explain the host either always be infected or not. If you’re saying there are rounds where only the host is infected then yeah it is unlikely (but can still happen), let me know if this is always the case.

2) I can take a look into adding a config, another issue though would be the infected can still trigger lockdown which means if you start the meltdown you’ll be stuck. I am however also adding config to fully configure the lockdown so you can keep entrance doors unlocked.

3) it should scale with the profit quota, if it’s not then let me know! (The minimum is 250, but as the profit quota increases it should be 50% of that instead).

**Comment by MrBl4ckSkull** [comment]
Ah, I see I guess I misunderstood how that setting works. I assumed it would allow for variable amounts of infected (So each player had a 30% chance to be an infected, but the max would be specified by number of players / players_per_infected, meaning you could have games with 0, 1, 2 or even 3 infected. I'm sure we had host as infected a considerable number of times though though, when nobody else was (but that may have been after we tweaked the configs a bit). Thanks for the insight! I look forward to new updates!!

**Comment by klampzlamps** [comment]
Just yesterday I was thinking a variable amount may work better and honestly I’ll probably change it to that. I like the idea of the dice roll per infected so the game is never predictable on how many there are. Thanks for the feedback!

**Comment by klampzlamps** [comment]
with v0.1.9 and v0.2.0 a variable amount of infected is now possible.

other changes, round quota now ramps up faster

Closing issue as comments have been addressed
