### ISSUE TITLE
posible options

### ISSUE THREAD

**Issue by xzelarx** [ControlCompany/InfectedCompany#12]
- an option in config to able or disable the screens, its bugging other mods for me like the openbodycams, the big cam when there's a qurantine
- and an option so one can use the fire exits to enter the facility again, i use the mimics mod, pretty difficult to know if u can use a fireexit already XD

**Comment by klampzlamps** [comment]
Added the first option, the ability to not disable ship monitors during quarantine in the config.

As for the 2nd point, allowing survivors to enter from the fire exits will make it too easy to escape the infected when quarantine starts.
