### ISSUE TITLE
As the host of the game im never the infected player

### ISSUE THREAD

**Issue by Bloocky999** [ControlCompany/InfectedCompany#13]
Im playing with 5 friends, they always are the infected, im never chosen.

**Comment by klampzlamps** [comment]
How many rounds? Its completely random so you probably just got unlucky.

I may add some “bad luck” protection.

**Comment by klampzlamps** [comment]
Added bad luck protection with v0.2.2, this should make it less likely a player never gets chosen

**Comment by Bloocky999** [comment]
Thanks, ill check it out
