### ISSUE TITLE
version 0.23 and 0.24 bug

### ISSUE THREAD

**Issue by sxwe1231** [ControlCompany/InfectedCompany#17]
During the game, some people may see a different dungeon terrain than others and cannot play normally. This problem does not exist in version 0.22.

**Comment by klampzlamps** [comment]
Hi!

I just released v0.2.5 that may fix this issue, it was difficult since I couldn't reproduce it but I added additional guardrails that _should_ prevent this from happening.

Were you using any other mods?

Thanks!

**Comment by sxwe1231** [comment]
Thank you very much, this module is really fun, this is our Thunderstore code 018e9cda-d967-fa4b-1658-bca0a884fb40, we will test it to see if there is any problem with 0.2.5

**Comment by sxwe1231** [comment]
SORRY，0.2.5 still has the same problem

**Comment by klampzlamps** [comment]
How often does it happen? Is it all players having different terrain or just some?

**Comment by sxwe1231** [comment]
https://youtu.be/JN0RQ2jFjuc?si=ijEoF1JkFekQ11LJ&t=45
The video starts at 45 seconds. Basically, there will be a problem every time. It will be divided into two groups. One group will display normally, and the other group will generate an error map. The door in the wrong map may not display properly.The number of players generating incorrect maps is usually relatively small.

**Comment by klampzlamps** [comment]
Could you paste the BepInEx logs for the players that have a mismatched map size? Can usually find the "LogOutput.log.X" logs in the "C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\BepInEx" folder

**Comment by klampzlamps** [comment]
I updated the mod again with v0.2.6, I added even more guardrails and checks but I still can't pinpoint the exact issue. Let me know if it still happens!

**Comment by sxwe1231** [comment]
Thank you very much for trying to solve this problem, I will wait for friends to test it with me.
But I guess it may be the impact of these settings in 0.2.3. I don’t understand the production of modules. This is just my idea.
「game_balance_change_map_size: If enabled, the map will be larger and have more scrap (default true)
game_balance_change_monster_spawn_rate: If enabled, maps will spawn more monsters (default true)」

**Comment by klampzlamps** [comment]
Yeah my changes for v0.2.6 were around those settings as well

**Comment by sxwe1231** [comment]
We'll also try setting these two to Off. Thank you

**Comment by klampzlamps** [comment]
Can you try with those settings on first? And if you encounter the issue you can disable them

**Comment by sxwe1231** [comment]
After testing, 0.2.6 seems to have solved this problem. We also tested that turning on [game_balance_change_map_size:] and [game_balance_change_monster_spawn_rate:] in 0.2.4 will cause a map de-sync issue. After closing these two settings, a map de-sync issue will occur. That's solved. At present, it is definitely caused by one of these two settings.

**Comment by sxwe1231** [comment]
We tested 0.2.6 which seems to resolve a map de-sync issue.
We tested that opening "game_balance_change_map_size:" and "game_balance_change_monster_spawn_rate" in 0.2.4 will cause a map de-sync issue.
But after turning off these two settings, there is no map error problem.
Thank you

**Comment by klampzlamps** [comment]
Thank you so much for testing this!! Really appreciate it and I’m glad it’s resolved now 😁
