### ISSUE TITLE
Panic makes it too easy to figure out infected players.

### ISSUE THREAD

**Issue by lxative** [ControlCompany/InfectedCompany#3]
all rounds quickly turned into a simple "who can panic" check to figure out the infected players. id recommend either giving the infected players the same ability or restricting its use to only those who are inside during quarantine. config options to modify/disable the ability would also be appreciated.

**Comment by klampzlamps** [comment]
you're absolutely right, will change so the infected can also use panic mode while not in monster mode

**Comment by klampzlamps** [comment]
changed in v0.1.3. Also added the config setting as suggested.
