### ISSUE TITLE
Rounds don't end with infected company

### ISSUE THREAD

**Issue by IIMadnessII** [ControlCompany/InfectedCompany#35]
After a recent update, V60 / V61 rounds don't manage to end game, just stuck after ship departure from the planet and the button to leave the planet still usable. The score is constantly being updated, but the new round doesn't start the game, just stacked. 

Here's my profile, sadly didn't make any pictures of any occurring errors. Code.:019166dd-0447-c7cb-c423-73be4730e062

**Comment by klampzlamps** [comment]
Fixed in v0.3.1
