### ISSUE TITLE
Mod softlock the cam when game end

### ISSUE THREAD

**Issue by Zodihack** [ControlCompany/InfectedCompany#38]
![ssssssssssge](https://github.com/user-attachments/assets/f2597b6e-5c7e-4f1c-a102-15a2476e44ba)
The camera goes on the ship, the takeoff don't start, nothing happen.

**Comment by Zodihack** [comment]
I played solo to check the mod

**Comment by Zodihack** [comment]
(yeah i stop spamming after that) the config 
## Settings file was created by plugin InfectedCompany v0.3.0
## Plugin GUID: InfectedCompany.InfectedCompany

[Client.GameSettings]

## Enables the alarm during quarantine.
# Setting type: Boolean
# Default value: true
quarantine_enable_alarm = true

## Enables the announcer during quarantine.
# Setting type: Boolean
# Default value: true
quarantine_enable_announcer = true

## Enables the Artifact whisper sound effect.
# Setting type: Boolean
# Default value: true
enable_artifact_whispers = true

[Debugging]

## Enables debugging logs.
# Setting type: Boolean
# Default value: false
enable_debug_version = false

[Host.GameSettings]

## Time in seconds for the infected kill cooldown (min 1).
# Setting type: Single
# Default value: 20
infected_kill_cooldown_in_seconds = 5

## Time in seconds that the infected mode lasts (min. 1).
# Setting type: Single
# Default value: 75
infected_mode_time_in_seconds = 75

## Time in seconds it takes for the insanity meter to fill up (min. 1).
# Setting type: Single
# Default value: 150
time_to_max_insanity_in_seconds = 150

## Percent damage reduction for the infected while they are transformed (min. 0).
# Setting type: Single
# Default value: 50
infected_mode_damage_reduction_percent = 50

## If enabled, the infected will auto transform when their insanity is full.
# Setting type: Boolean
# Default value: false
auto_start_infected_mode_when_insanity_max = false

## Allow infected to know other infected by highlighting their in-game player names.
# Setting type: Boolean
# Default value: true
highlight_infected_player_names = true

## Allow players to use panic mode.
# Setting type: Boolean
# Default value: true
allow_panic_mode = false

## Percent that infected will be chosen for the round. This chance is rolled for each infected. (min. 0 = never, max 100 = always).
# Setting type: Single
# Default value: 100
infected_percent_chance = 8

## Time in seconds it takes to use the exit doors during quarantine. (min. 1).
# Setting type: Single
# Default value: 10
quarantine_entrance_exit_use_time_in_seconds = 10

## Tag your public server with [INFECTED COMPANY].
# Setting type: Boolean
# Default value: true
tag_public_server = false

## Number of players per infected (min. 1). For example, if this is 3.5 then every 3.5 players another will be chosen as an infected. There is always at least 1 infected in the game.
# Setting type: Single
# Default value: 3.5
players_per_infected = 3.5

## Number of players required to start the game (min. 1).
# Setting type: Int32
# Default value: 1
number_of_players_required_to_start = 1

## Minimum quota for the round for survivors to win.
# Setting type: Int32
# Default value: 250
min_round_quota_for_survivor_win = 250

[Host.GameSettings.GameBalance]

## Survivors can only start the ship after this hour (24-hour clock format).
# Setting type: Int32
# Default value: 19
game_balance_can_start_ship_after_hour = 1

## If enabled, the profit quota will increase at a different rate than normal.
# Setting type: Boolean
# Default value: true
game_balance_change_profit_quota = false

## If enabled, the map will be larger and have more scrap.
# Setting type: Boolean
# Default value: true
game_balance_change_map_size = false

## If enabled, maps will spawn more monsters.
# Setting type: Boolean
# Default value: true
game_balance_change_monster_spawn_rate = false

## If enabled, vanilla moon prices will be changed.
# Setting type: Boolean
# Default value: true
game_balance_change_moon_prices = false

## If enabled, some item's prices will be changed (such as the shovel).
# Setting type: Boolean
# Default value: true
game_balance_change_item_prices = false

[Host.GameSettings.Quarantine]

## If enabled, ship monitors will be disabled during quarantine.
# Setting type: Boolean
# Default value: true
quarantine_disable_ship_monitor = true

## If enabled, the terminal will be disabled during quarantine.
# Setting type: Boolean
# Default value: true
quarantine_disable_terminal = true

[Keybinds]

# Setting type: String
# Default value: p
panic_drop_all_items = p

[Keybinds.InfectedMode]

# Setting type: String
# Default value: x
enter_infected_mode = x

# Setting type: String
# Default value: x
exit_infected_mode = x

# Setting type: String
# Default value: z
infected_mode_attack = f

**Comment by klampzlamps** [comment]
This has been resolved in v0.3.1
