### ISSUE TITLE
bug with HDlethalcompany

### ISSUE THREAD

**Issue by 1410677474** [ControlCompany/InfectedCompany#4]
Causes map generator to get stuck in seed

**Comment by klampzlamps** [comment]
How often does this happen? Are you running other mods?

**Comment by 1410677474** [comment]
no，only



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 25, 2024 21:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ControlCompany/InfectedCompany] bug with HDlethalcompany (Issue#4)




 
How often does this happen? Are you running other mods?

**Comment by 1410677474** [comment]
100%

**Comment by klampzlamps** [comment]
fixed with v0.1.4. Thanks for reporting the issue! Really appreciate it.
