### ISSUE TITLE
The ship can't leave the moon properly

### ISSUE THREAD

**Issue by habacksill** [ControlCompany/InfectedCompany#42]
I made a mod set, and I did a test for the mod error. 
The ship didn't leave the moon properly, The ship return to the moon, and the start lever was jammed, time wasn't stop.
Please fix it as soon as possible.
and also I couldn't kill the people when I was infected

**Comment by DistortioN322** [comment]
how are u fix it?

**Comment by habacksill** [comment]
> 어떻게 고칠 수 있습니까?

it already fixed at v0.3.1 the latest version
