### ISSUE TITLE
Some enemy-specific issues when infected

### ISSUE THREAD

**Issue by MrBl4ckSkull** [ControlCompany/InfectedCompany#5]
Really good, well made mod!
Yesterday when playing with some friends, the infected transformed into the monster. While searching for survivors, a snare flea landed on his head and killed him, which doesn't seem intentional. Perhaps snare fleas shouldn't be triggered if transformed, or if one does get on your head you should be able to kill it.

Not really an issue but something I'd like to note, while playing we had the the infected get snatched by a bracken while untransformed. I'm not sure how the bracken behaves while transformed. Obviously that's not a problem that it can kill you, but I'm wondering if there's a way to add a configuration where monsters ignore the infected player even when untransformed, but that may make it too easy to clear uninfected individuals. Perhaps infected individuals should be immune to monsters like the bracken, or give the infected the ability to 'respawn' if killed by a monster or something. I know monsters are a part of the game, but it feels a little lame when the infected dies due to something like a bracken meaning there's no threat for the remaining survivors.

Lastly, we had games where survivors completed the quota before the infected got to transform, and pulled the dropship lever. What if there was a soft limit on when the lever can be pulled (For example, it cannot be pulled before 2pm) or maybe leaving should be an (anonymous) decision that needs to be unanimously agreed upon by all living players (non-infected) players being on the ship. Knowing you, yourself, are not the infected and leaving everyone else behind because you reached the round quota also feels a little lame.

Those things are just nitpicks. I really look forward to the future development of this mod! So far its made to an outstanding quality, and it works incredibly well. Keep up the good work!!

**Comment by klampzlamps** [comment]
I’ll look into the snare flea, it’s not intended that it can kill you while transformed.

As for the round quota, I like the idea of the vote and may experiment with it. As a quick solve, you can actually configure the minimum round quota so you can increase this in the config file.

I’m still gathering feedback for the default values so this was really helpful!

Thanks for trying out the mod!

**Comment by klampzlamps** [comment]
There are many other configuration settings to balance the game however you like, such as time it takes to fill up insanity, infected transformation duration, kill cooldown, etc… 

Let me know what works for you and your group!
