### ISSUE TITLE
Are custom suits supported?

### ISSUE THREAD

**Issue by reithegoat** [ControlCompany/InfectedCompany#6]
Are custom suit mods supported? Specifically, mods that add new suit _textures_, like [More Suits](https://thunderstore.io/c/lethal-company/p/x753/More_Suits/) and [AdditionalSuits](https://thunderstore.io/c/lethal-company/p/AlexCodesGames/AdditionalSuits/) and not the mods that completely change the player model.

**Comment by klampzlamps** [comment]
Maybe, I haven’t tested with suit modifications and as long as those mods don’t completely replace the player object then it should work. Let me know though.

**Comment by reithegoat** [comment]
Custom suit mods work! The one tested is the AdditionalSuits mod. It works with the "transformation" animation as well.
